import sys

print("Python Version Compatibility Information")
print("=======================================\n")
print(f"Current Python version: {sys.version_info.major}.{sys.version_info.minor}.{sys.version_info.micro}")
print("\nThis application requires Python 3.10-3.12 and several dependencies")
print("that are not compatible with your current Python installation.\n")
print("To run this application, you would need to:")
print("1. Install Python 3.10 or 3.11")
print("2. Install the required dependencies from requirements.txt")
print("3. Set up API keys for OpenAI and Tavily\n")
print("Application Overview:")
print("-------------------")
print("The Market Research & Use Case Generation Multi-Agent System is designed")
print("to generate AI use cases for specific industries or companies.")
print("\nIt uses a multi-agent architecture with three specialized agents:")
print("- Industry Research Agent: Researches and analyzes the industry/company")
print("- Use Case Generation Agent: Creates relevant AI/GenAI use cases")
print("- Resource Asset Collection Agent: Finds datasets and resources for implementation\n")
print("When properly set up, you can run the application using:")
print("- Command line: python market_research_agent.py")
print("- Web interface: streamlit run app.py\n")
print("For more information, please refer to the README_DOCUMENTATION.md file.")